---

- name: Copies correct PostgreSQL config file over
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Enable and Start PostgreSQL
  service:
    name: postgresql-9.6
    state: started
    enabled: yes
  become: true
